### PR TITLE
Docker/Docker compose with multi stage build for kanban app

### PR DESCRIPTION
**Pull request by arnabrahman**
Fixes #

- [ ] Does not depend on other PRs
- [x] Depends on other PR being merged first: #279 

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [ ] New feature
- [ ] Refactor
- [x] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
Docker compose prod & local
## What was done
* Docker compose for prod & dev
* Docker file for prod & dev
* Multi stage build in prod dockerfile
## How to test

- [ ] Needs regression testing (add QA needed label)

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

## Reminder list

- Determine whether REST API Documentation should be updated
- Make an assessment on whether unit tests should be updated and/or added
- Ensure follow up tasks are linked to this PR

QA - if regression testing was requested:

- [ ] QA has verified

### CODE REVIEW

**Review by musfique-m — APPROVED** [review]
Looks good.

**Comment by musfique-m** [comment]
Please remove the merge conflict.

**Comment by arnabrahman** [comment]
> Please remove the merge conflict.

Removed [f97397f](https://github.com/CraftsmenLtd/coe-batch-q322/pull/294/commits/f97397f43d0692c51caa0e85d7e6da850d98e300)

**Review by musfique-m — APPROVED** [review]
Tested by code inspection.
Looks good.

**Pull request merged**
